//
//  APCopyVC.swift
//  Untitled
//
//  Created by bennour.dz@gmail.com on 30/11/2016, using AnimaApp.com, under MIT license.
//  Copyright © 2016 Company Name. All rights reserved.
//

import UIKit

public class APCopyVC : ANViewController {
    
    @IBOutlet weak var cellReadingListCopy9: UIView?
    @IBOutlet weak var cellReadingListCopy9Background: UIView?
    @IBOutlet weak var cellReadingListCopy9Separator: UIImageView?
    @IBOutlet weak var cellReadingListCopy9ArtieTheStrongestManInTheWorld: UIView?
    @IBOutlet weak var cellReadingListCopy9Label: UILabel?
    @IBOutlet weak var cellReadingListCopy9Label1: UILabel?
    @IBOutlet weak var cellReadingListCopy9BackChevron: UIImageView?
    @IBOutlet weak var cellReadingListCopy8: UIView?
    @IBOutlet weak var cellReadingListCopy8Background: UIView?
    @IBOutlet weak var cellReadingListCopy8Separator: UIImageView?
    @IBOutlet weak var cellReadingListCopy8ArtieTheStrongestManInTheWorld: UIView?
    @IBOutlet weak var cellReadingListCopy8Label: UILabel?
    @IBOutlet weak var cellReadingListCopy8Label1: UILabel?
    @IBOutlet weak var cellReadingListCopy8BackChevron: UIImageView?
    @IBOutlet weak var cellReadingListCopy7: UIView?
    @IBOutlet weak var cellReadingListCopy7Background: UIView?
    @IBOutlet weak var cellReadingListCopy7Separator: UIImageView?
    @IBOutlet weak var cellReadingListCopy7ArtieTheStrongestManInTheWorld: UIView?
    @IBOutlet weak var cellReadingListCopy7Label: UILabel?
    @IBOutlet weak var cellReadingListCopy7Label1: UILabel?
    @IBOutlet weak var cellReadingListCopy7BackChevron: UIImageView?
    @IBOutlet weak var navigationBarSubtitle: UIView?
    @IBOutlet weak var navigationBarSubtitleBar: UIImageView?
    @IBOutlet weak var icmenu: UIView?
    @IBOutlet weak var icmenuIcon24Px: UIView?
    @IBOutlet weak var icmenuIcon24PxShape: UIImageView?
    @IBOutlet weak var backChevron: UIImageView?
    @IBOutlet weak var group4: UIView?
    @IBOutlet weak var group4CellCellWithIcon: UIView?
    @IBOutlet weak var group4CellCellWithIconCellBackground: UIView?
    @IBOutlet weak var group4CellCellWithIconSeparator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconGroup3: UIView?
    @IBOutlet weak var group4CellCellWithIconGroup3DisclosureIndicator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconGroup3Label: UILabel?
    @IBOutlet weak var group4CellCellWithIconGroup3Label1432: UILabel?
    @IBOutlet weak var group4CellCellWithIconGroup3Group2: UIView?
    @IBOutlet weak var group4CellCellWithIconGroup3Group2IconShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconGroup3Group2Calendar3: UIView?
    @IBOutlet weak var group4CellCellWithIconGroup3Group2Calendar3Layer1: UIView?
    @IBOutlet weak var group4CellCellWithIconGroup3Group2Calendar3Layer1Group: UIView?
    @IBOutlet weak var group4CellCellWithIconGroup3Group2Calendar3Layer1GroupShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconGroup3Group2Calendar3Layer1GroupImage1: UIImageView?
    @IBOutlet weak var group4CellCellWithIconGroup3Group2Calendar3Layer1GroupImage2: UIImageView?
    @IBOutlet weak var group4CellCellWithIconGroup3Group2Calendar3Layer1GroupImage3: UIImageView?
    @IBOutlet weak var group4CellCellWithIconGroup3Group2Calendar3Layer1GroupImage4: UIImageView?
    @IBOutlet weak var group4CellCellWithIconGroup3Group2Calendar3Layer1GroupImage5: UIImageView?
    @IBOutlet weak var group4CellCellWithIconGroup3Group2Calendar3Layer1GroupImage6: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy11: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy11CellBackground: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy11Separator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy11Group3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy11Group3DisclosureIndicator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy11Group3Label: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy11Group3Label1432: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy11Group3Group2: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy11Group3Group2IconShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy11Group3Group2Calendar3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy11Group3Group2Calendar3Layer1: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy11Group3Group2Calendar3Layer1Group: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy11Group3Group2Calendar3Layer1GroupShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy11Group3Group2Calendar3Layer1GroupImage1: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy11Group3Group2Calendar3Layer1GroupImage2: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy11Group3Group2Calendar3Layer1GroupImage3: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy11Group3Group2Calendar3Layer1GroupImage4: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy11Group3Group2Calendar3Layer1GroupImage5: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy11Group3Group2Calendar3Layer1GroupImage6: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy10: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy10CellBackground: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy10Separator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy10Group3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy10Group3DisclosureIndicator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy10Group3Label: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy10Group3Label1432: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy10Group3Group2: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy10Group3Group2IconShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy10Group3Group2Calendar3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy10Group3Group2Calendar3Layer1: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy10Group3Group2Calendar3Layer1Group: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy10Group3Group2Calendar3Layer1GroupShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy10Group3Group2Calendar3Layer1GroupImage1: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy10Group3Group2Calendar3Layer1GroupImage2: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy10Group3Group2Calendar3Layer1GroupImage3: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy10Group3Group2Calendar3Layer1GroupImage4: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy10Group3Group2Calendar3Layer1GroupImage5: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy10Group3Group2Calendar3Layer1GroupImage6: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy9: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy9CellBackground: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy9Separator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy9Group3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy9Group3DisclosureIndicator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy9Group3Label: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy9Group3Label1432: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy9Group3Group2: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy9Group3Group2IconShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy9Group3Group2Calendar3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy9Group3Group2Calendar3Layer1: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy9Group3Group2Calendar3Layer1Group: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy9Group3Group2Calendar3Layer1GroupShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy9Group3Group2Calendar3Layer1GroupImage1: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy9Group3Group2Calendar3Layer1GroupImage2: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy9Group3Group2Calendar3Layer1GroupImage3: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy9Group3Group2Calendar3Layer1GroupImage4: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy9Group3Group2Calendar3Layer1GroupImage5: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy9Group3Group2Calendar3Layer1GroupImage6: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy8: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy8CellBackground: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy8Separator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy8Group3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy8Group3DisclosureIndicator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy8Group3Label: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy8Group3Label1432: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy8Group3Group2: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy8Group3Group2IconShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy8Group3Group2Calendar3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy8Group3Group2Calendar3Layer1: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy8Group3Group2Calendar3Layer1Group: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy8Group3Group2Calendar3Layer1GroupShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy8Group3Group2Calendar3Layer1GroupImage1: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy8Group3Group2Calendar3Layer1GroupImage2: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy8Group3Group2Calendar3Layer1GroupImage3: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy8Group3Group2Calendar3Layer1GroupImage4: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy8Group3Group2Calendar3Layer1GroupImage5: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy8Group3Group2Calendar3Layer1GroupImage6: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy7: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy7CellBackground: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy7Separator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy7Group3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy7Group3DisclosureIndicator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy7Group3Label: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy7Group3Label1432: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy7Group3Group2: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy7Group3Group2IconShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy7Group3Group2Calendar3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy7Group3Group2Calendar3Layer1: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy7Group3Group2Calendar3Layer1Group: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy7Group3Group2Calendar3Layer1GroupShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy7Group3Group2Calendar3Layer1GroupImage1: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy7Group3Group2Calendar3Layer1GroupImage2: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy7Group3Group2Calendar3Layer1GroupImage3: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy7Group3Group2Calendar3Layer1GroupImage4: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy7Group3Group2Calendar3Layer1GroupImage5: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy7Group3Group2Calendar3Layer1GroupImage6: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy6: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy6CellBackground: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy6Separator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy6Group3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy6Group3DisclosureIndicator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy6Group3Label: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy6Group3Label1432: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy6Group3Group2: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy6Group3Group2IconShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy6Group3Group2Calendar3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy6Group3Group2Calendar3Layer1: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy6Group3Group2Calendar3Layer1Group: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy6Group3Group2Calendar3Layer1GroupShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy6Group3Group2Calendar3Layer1GroupImage1: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy6Group3Group2Calendar3Layer1GroupImage2: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy6Group3Group2Calendar3Layer1GroupImage3: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy6Group3Group2Calendar3Layer1GroupImage4: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy6Group3Group2Calendar3Layer1GroupImage5: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy6Group3Group2Calendar3Layer1GroupImage6: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy5: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy5CellBackground: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy5Separator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy5Group3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy5Group3DisclosureIndicator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy5Group3Label: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy5Group3Label1432: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy5Group3Group2: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy5Group3Group2IconShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy5Group3Group2Calendar3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy5Group3Group2Calendar3Layer1: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy5Group3Group2Calendar3Layer1Group: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy5Group3Group2Calendar3Layer1GroupShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy5Group3Group2Calendar3Layer1GroupImage1: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy5Group3Group2Calendar3Layer1GroupImage2: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy5Group3Group2Calendar3Layer1GroupImage3: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy5Group3Group2Calendar3Layer1GroupImage4: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy5Group3Group2Calendar3Layer1GroupImage5: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy5Group3Group2Calendar3Layer1GroupImage6: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy4: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy4CellBackground: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy4Separator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy4Group3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy4Group3DisclosureIndicator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy4Group3Label: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy4Group3Label1432: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy4Group3Group2: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy4Group3Group2IconShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy4Group3Group2Calendar3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy4Group3Group2Calendar3Layer1: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy4Group3Group2Calendar3Layer1Group: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy4Group3Group2Calendar3Layer1GroupShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy4Group3Group2Calendar3Layer1GroupImage1: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy4Group3Group2Calendar3Layer1GroupImage2: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy4Group3Group2Calendar3Layer1GroupImage3: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy4Group3Group2Calendar3Layer1GroupImage4: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy4Group3Group2Calendar3Layer1GroupImage5: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy4Group3Group2Calendar3Layer1GroupImage6: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy3CellBackground: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy3Separator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy3Group3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy3Group3DisclosureIndicator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy3Group3Label: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy3Group3Label1432: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy3Group3Group2: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy3Group3Group2IconShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy3Group3Group2Calendar3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy3Group3Group2Calendar3Layer1: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy3Group3Group2Calendar3Layer1Group: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy3Group3Group2Calendar3Layer1GroupShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy3Group3Group2Calendar3Layer1GroupImage1: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy3Group3Group2Calendar3Layer1GroupImage2: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy3Group3Group2Calendar3Layer1GroupImage3: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy3Group3Group2Calendar3Layer1GroupImage4: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy3Group3Group2Calendar3Layer1GroupImage5: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy3Group3Group2Calendar3Layer1GroupImage6: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy2: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy2CellBackground: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy2Separator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy2Group3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy2Group3DisclosureIndicator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy2Group3Label: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy2Group3Label1432: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopy2Group3Group2: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy2Group3Group2IconShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy2Group3Group2Calendar3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy2Group3Group2Calendar3Layer1: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy2Group3Group2Calendar3Layer1Group: UIView?
    @IBOutlet weak var group4CellCellWithIconCopy2Group3Group2Calendar3Layer1GroupShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy2Group3Group2Calendar3Layer1GroupImage1: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy2Group3Group2Calendar3Layer1GroupImage2: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy2Group3Group2Calendar3Layer1GroupImage3: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy2Group3Group2Calendar3Layer1GroupImage4: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy2Group3Group2Calendar3Layer1GroupImage5: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy2Group3Group2Calendar3Layer1GroupImage6: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopy: UIView?
    @IBOutlet weak var group4CellCellWithIconCopyCellBackground: UIView?
    @IBOutlet weak var group4CellCellWithIconCopySeparator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopyGroup3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopyGroup3DisclosureIndicator: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopyGroup3Label: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopyGroup3Label1432: UILabel?
    @IBOutlet weak var group4CellCellWithIconCopyGroup3Group2: UIView?
    @IBOutlet weak var group4CellCellWithIconCopyGroup3Group2IconShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopyGroup3Group2Calendar3: UIView?
    @IBOutlet weak var group4CellCellWithIconCopyGroup3Group2Calendar3Layer1: UIView?
    @IBOutlet weak var group4CellCellWithIconCopyGroup3Group2Calendar3Layer1Group: UIView?
    @IBOutlet weak var group4CellCellWithIconCopyGroup3Group2Calendar3Layer1GroupShape: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopyGroup3Group2Calendar3Layer1GroupImage1: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopyGroup3Group2Calendar3Layer1GroupImage2: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopyGroup3Group2Calendar3Layer1GroupImage3: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopyGroup3Group2Calendar3Layer1GroupImage4: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopyGroup3Group2Calendar3Layer1GroupImage5: UIImageView?
    @IBOutlet weak var group4CellCellWithIconCopyGroup3Group2Calendar3Layer1GroupImage6: UIImageView?
    @IBOutlet weak var group4View1: UIView?
    @IBOutlet weak var group4View1CellBackground: UIView?
    @IBOutlet weak var group4View1Separator: UIImageView?
    @IBOutlet weak var group4View1Group3: UIView?
    @IBOutlet weak var group4View1Group3DisclosureIndicator: UIImageView?
    @IBOutlet weak var group4View1Group3Label: UILabel?
    @IBOutlet weak var group4View1Group3Label1432: UILabel?
    @IBOutlet weak var group4View1Group3Group2: UIView?
    @IBOutlet weak var group4View1Group3Group2IconShape: UIImageView?
    @IBOutlet weak var group4View1Group3Group2Calendar3: UIView?
    @IBOutlet weak var group4View1Group3Group2Calendar3Layer1: UIView?
    @IBOutlet weak var group4View1Group3Group2Calendar3Layer1Group: UIView?
    @IBOutlet weak var group4View1Group3Group2Calendar3Layer1GroupShape: UIImageView?
    @IBOutlet weak var group4View1Group3Group2Calendar3Layer1GroupImage1: UIImageView?
    @IBOutlet weak var group4View1Group3Group2Calendar3Layer1GroupImage2: UIImageView?
    @IBOutlet weak var group4View1Group3Group2Calendar3Layer1GroupImage3: UIImageView?
    @IBOutlet weak var group4View1Group3Group2Calendar3Layer1GroupImage4: UIImageView?
    @IBOutlet weak var group4View1Group3Group2Calendar3Layer1GroupImage5: UIImageView?
    @IBOutlet weak var group4View1Group3Group2Calendar3Layer1GroupImage6: UIImageView?
    @IBOutlet weak var group2: UIView?
    @IBOutlet weak var group2Label: UILabel?
    @IBOutlet weak var group2Label1432: UILabel?

    

}